name:                kaban
version:             0.1.0.0
github:              "fycth/kaban"
license:             BSD3
author:              "Andrii Sergiienko"
maintainer:          "andrey.sergienko@gmail.com"
copyright:           "2019 Andrii Sergiienko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fycth/kaban#readme>

dependencies:
- base-noprelude >= 4.12 && < 4.13
- relude >= 0.4.0 && < 0.4.1
- network
- binary
- bytestring
- bytestring-conversion
- hex

default-extensions:
- OverloadedStrings
- NoImplicitPrelude

library:
  source-dirs: src

executables:
  kaban-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall 
    - -Wcompat 
    - -Wincomplete-record-updates 
    - -Wincomplete-uni-patterns 
    - -Wredundant-constraints
    dependencies:
    - kaban

tests:
  kaban-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kaban
